The /proc exodus, and a little safety paranoia on $tmpfile

diff --git a/zrep b/zrep
--- a/zrep
+++ b/zrep
@@ -238,6 +238,9 @@ rm $zrep_checkfile
 
 Z_LOCK_RETRY=${Z_LOCK_RETRY:-10}  # default 10 second  retry, 1 per sec
 Z_SAVE_COUNT=${Z_SAVE_COUNT:-5}
+
+# This is named like a global override. and CAN be overridden by user.
+# But should only be used in zrep_vars module
 Z_GLOBAL_LOCKFILE=$ZREP_RUNDIR/zrep.lock
 
 if [[ "$Z_GLOBAL_PID" == "" ]] ; then
@@ -253,7 +256,7 @@ Z_SETHOLD=${Z_SETHOLD:-"zfs hold"}
 
 # return PID of proc holding global lock, or nothing
 zrep_global_lock_pid(){
-	$LS -l $Z_GLOBAL_LOCKFILE 2>/dev/null |awk -F/ '{print $NF}'
+	cat $Z_GLOBAL_LOCKFILE 2>/dev/null
 }
 
 # return 0 if "we" are holding lock, 1 otherwise
@@ -277,14 +280,15 @@ zrep_has_global_lock(){
 
 #Note: it is an ERROR to call this if you already have lock
 #It is binary, not recursive ownership.
+#We do NOT try to clean up stale global lock.
+#This is a shortterm lock. It should never be stale. If it is,
+#it could indicate a more serious system/zrep problem happening.
 zrep_get_global_lock(){
 	typeset retry_count=$Z_LOCK_RETRY
 	typeset lockpid
 
-
-	[[ -d /proc/$$ ]] || zrep_errquit "/proc fs must be functional to use zrep"
-
-	$LN_S /proc/$Z_GLOBAL_PID $Z_GLOBAL_LOCKFILE && return 0
+	set -C
+	echo $Z_GLOBAL_PID > $Z_GLOBAL_LOCKFILE && return 0
 
 	# otherwise, deal with fail
 	# Careful of race conditions on stale CLEAN UP!
@@ -298,10 +302,14 @@ zrep_get_global_lock(){
 	# For now, must request manual cleanup
 	while (( retry_count > 0 )); do
 		sleep 1
-		$LN_S /proc/$Z_GLOBAL_PID $Z_GLOBAL_LOCKFILE && return 0
+		echo $Z_GLOBAL_PID > $Z_GLOBAL_LOCKFILE && return 0
 		retry_count=$((retry_count-1))
 		lockpid=`zrep_global_lock_pid`
-		if [[ ! -d /proc/$lockpid ]] ; then
+		if [[ "$lockpid" -le 0 ]] ; then
+			zrep_errquit ERROR: invalid contents for global lock file $Z_GLOBAL_LOCKFILE
+		fi
+		kill -0 $lockpid 2>/dev/null
+		if [[ $? -ne 0 ]] ; then
 			_errprint ERROR: stale global lock file
 			_errprint ERROR: shut down ALL zrep instances, then manually remove
 			_errprint $Z_GLOBAL_LOCKFILE
@@ -349,7 +357,7 @@ zrep_lock_fs(){
 	typeset check=`zrep_fs_lock_pid $1` newcheck
 	if [[ "$check" != "" ]] ; then
 		# See if owning process still exists.
-		ls -d /proc/$check >/dev/null 2>&1 && return 1
+		kill -0 $check 2>/dev/null && return 1
 	fi
 
 	zrep_get_global_lock
@@ -360,13 +368,14 @@ zrep_lock_fs(){
 		return 1
 	fi
 
-	# Double-check if needed, now that we have global lock
+	# Yes we already checked this, but we didnt have global lock.
+	# Avoid race condition and doublecheck now that we have global lock.
 	if [[ "$check" != "" ]] ; then
 		newcheck=`zrep_fs_lock_pid $1`
 		if [[ "$newcheck" != "$check" ]] && [[ "$newcheck" != "" ]]
 		then
-			# oops. someone else must have dealt with it.
-			# If they havent reset it then give up
+			# oops. someone else beat us to it.
+			# Better luck next time.
 			zrep_release_global_lock
 			return 1
 		fi
@@ -1846,6 +1855,7 @@ _expire(){
 		zrep_errquit ${ZREPTAG}:savecount on $1 set to improper value $savecount
 	fi
 
+	rm -f $tmpfile
 	if [[ "$master" == "yes" ]] ; then
 		lastsent=`getlastsnapsent $1`
 		if [[ "$lastsent" == "" ]] ; then
