added "all" option to snapnonly and synconly

diff --git a/zrep b/zrep
--- a/zrep
+++ b/zrep
@@ -908,6 +908,13 @@ list_autosnaps(){
 zrep_snaponly(){
 	typeset srcfs
 
+	if [[ "$1" == "all" ]] ; then
+		set -- `zrep_list_master`
+		if [[ "$1" == "" ]] ; then
+			exit
+		fi
+	fi
+
 	while [[ "$1" != "" ]] ; do
 		srcfs="$1" ;shift
 		zrep_lock_fs $srcfs
@@ -1630,28 +1637,38 @@ zrep_synconly(){
 #	we can skip retries, though.
 	typeset srcfs desthost destfs
 
-	# at one point, accept multiple args. But not for now...?
-	srcfs=$1
-
-	[[ "$srcfs" == "" ]] && zrep_errquit No fileystem specified for synconly
-
-	desthost=`$ZFSGETVAL ${ZREPTAG}:dest-host $srcfs`
-	destfs=`$ZFSGETVAL ${ZREPTAG}:dest-fs $srcfs`
-	if [[ $? -ne 0 ]] || [[ "$desthost" == "-" ]] || [[ "$destfs" == "-" ]];
-	then
-		zrep_errquit Problem getting zrep properties for fs $srcfs
+	if [[ "$1" == "all" ]] ; then
+		set -- `zrep_list_master`
+		if [[ "$1" == "" ]] ; then
+			exit
+		fi
 	fi
 
-	zrep_lock_fs $srcfs
-	if [[ $? -ne 0 ]] ; then
-		zrep_errquit Failed to acquire zrep lock for $srcfs
-	fi
+	[[ "$1" == "" ]] && zrep_errquit No fileystem specified for synconly
 
-	_sync $srcfs $desthost $destfs || zrep_errquit sync failed for $srcfs
+	while [[ "$1" != "" ]] ; do
+		srcfs=$1
 
-	_expire $srcfs	#dont care so much if this fails
 
-	zrep_unlock_fs $srcfs
+		desthost=`$ZFSGETVAL ${ZREPTAG}:dest-host $srcfs`
+		destfs=`$ZFSGETVAL ${ZREPTAG}:dest-fs $srcfs`
+		if [[ $? -ne 0 ]] || [[ "$desthost" == "-" ]] || [[ "$destfs" == "-" ]];
+		then
+			zrep_errquit Problem getting zrep properties for fs $srcfs
+		fi
+
+		zrep_lock_fs $srcfs
+		if [[ $? -ne 0 ]] ; then
+			zrep_errquit Failed to acquire zrep lock for $srcfs
+		fi
+
+		_sync $srcfs $desthost $destfs || zrep_errquit sync failed for $srcfs
+
+		_expire $srcfs	#dont care so much if this fails
+
+		zrep_unlock_fs $srcfs
+
+	done
 }
 
 
@@ -2265,8 +2282,8 @@ usage(){
 	print '      more recently than the given amount of seconds'
 	print
 	print 'Paired commands for high-transaction systems:'
-	print '   zrep snaponly ZFS/fs'
-	print '   zrep synconly ZFS/fs'
+	print '   zrep snaponly (ZFS/fs ... |all)'
+	print '   zrep synconly (ZFS/fs ...|all)'
 	print 'The above two commands split the simple sync subcommand, into two'
 	print 'separate steps, so that a database, etc. may resume while the sync'
 	print 'completes in the background'
diff --git a/zrep_sync b/zrep_sync
--- a/zrep_sync
+++ b/zrep_sync
@@ -357,28 +357,38 @@ zrep_synconly(){
 #	we can skip retries, though.
 	typeset srcfs desthost destfs
 
-	# at one point, accept multiple args. But not for now...?
-	srcfs=$1
-
-	[[ "$srcfs" == "" ]] && zrep_errquit No fileystem specified for synconly
-
-	desthost=`$ZFSGETVAL ${ZREPTAG}:dest-host $srcfs`
-	destfs=`$ZFSGETVAL ${ZREPTAG}:dest-fs $srcfs`
-	if [[ $? -ne 0 ]] || [[ "$desthost" == "-" ]] || [[ "$destfs" == "-" ]];
-	then
-		zrep_errquit Problem getting zrep properties for fs $srcfs
+	if [[ "$1" == "all" ]] ; then
+		set -- `zrep_list_master`
+		if [[ "$1" == "" ]] ; then
+			exit
+		fi
 	fi
 
-	zrep_lock_fs $srcfs
-	if [[ $? -ne 0 ]] ; then
-		zrep_errquit Failed to acquire zrep lock for $srcfs
-	fi
+	[[ "$1" == "" ]] && zrep_errquit No fileystem specified for synconly
 
-	_sync $srcfs $desthost $destfs || zrep_errquit sync failed for $srcfs
+	while [[ "$1" != "" ]] ; do
+		srcfs=$1
 
-	_expire $srcfs	#dont care so much if this fails
 
-	zrep_unlock_fs $srcfs
+		desthost=`$ZFSGETVAL ${ZREPTAG}:dest-host $srcfs`
+		destfs=`$ZFSGETVAL ${ZREPTAG}:dest-fs $srcfs`
+		if [[ $? -ne 0 ]] || [[ "$desthost" == "-" ]] || [[ "$destfs" == "-" ]];
+		then
+			zrep_errquit Problem getting zrep properties for fs $srcfs
+		fi
+
+		zrep_lock_fs $srcfs
+		if [[ $? -ne 0 ]] ; then
+			zrep_errquit Failed to acquire zrep lock for $srcfs
+		fi
+
+		_sync $srcfs $desthost $destfs || zrep_errquit sync failed for $srcfs
+
+		_expire $srcfs	#dont care so much if this fails
+
+		zrep_unlock_fs $srcfs
+
+	done
 }
 
 
